"""Generate a PyInstaller VERSIONINFO resource file from version.py.

PyInstaller's EXE(version=...) expects a path to a file matching the format
documented at https://pyinstaller.org/en/stable/spec-files.html#capturing-windows-version-data
— it's just a Python literal for a VSVersionInfo struct. Regenerating it on
every build keeps the Windows "Properties → Details" tab in sync with
version.py.

This module is imported from Rudi.spec at build time and also works as a
standalone script for manual inspection:

    .venv\\Scripts\\python.exe installer\\version_info.py
"""
from __future__ import annotations

from pathlib import Path


def _load_version(project_root: Path) -> str:
    ns: dict = {}
    exec((project_root / "version.py").read_text(encoding="utf-8"), ns)
    return str(ns["__version__"])


def _version_tuple(v: str) -> tuple[int, int, int, int]:
    parts = [int(p) for p in v.split(".") if p.isdigit()]
    while len(parts) < 4:
        parts.append(0)
    return tuple(parts[:4])  # type: ignore[return-value]


def write_version_file(project_root: Path, out_path: Path) -> Path:
    """Write a PyInstaller version resource file and return its path."""
    version = _load_version(project_root)
    vt = _version_tuple(version)
    content = f'''# Auto-generated by installer/version_info.py — do not edit by hand.
VSVersionInfo(
    ffi=FixedFileInfo(
        filevers={vt!r},
        prodvers={vt!r},
        mask=0x3f,
        flags=0x0,
        OS=0x40004,
        fileType=0x1,
        subtype=0x0,
        date=(0, 0),
    ),
    kids=[
        StringFileInfo([
            StringTable(
                u"040904B0",
                [
                    StringStruct(u"CompanyName", u"Nathan Ladd"),
                    StringStruct(u"FileDescription", u"Rudi quiz engine"),
                    StringStruct(u"FileVersion", u"{version}"),
                    StringStruct(u"InternalName", u"Rudi"),
                    StringStruct(u"LegalCopyright", u"© Nathan Ladd"),
                    StringStruct(u"OriginalFilename", u"Rudi.exe"),
                    StringStruct(u"ProductName", u"Rudi"),
                    StringStruct(u"ProductVersion", u"{version}"),
                ],
            )
        ]),
        VarFileInfo([VarStruct(u"Translation", [1033, 1200])]),
    ],
)
'''
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    return out_path


if __name__ == "__main__":
    root = Path(__file__).resolve().parent.parent
    out = write_version_file(root, root / "build" / "file_version_info.txt")
    print(f"wrote {out}")
